[package]
name = "desktop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu = { path = "../emu" }
fltk = "^1"
